spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:62162;databaseName=Cafe_Pos;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- Hibernate Configuration ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#File Upload Settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

#Path Store Uploaded Product Images
app.upload.products-dir=uploads/products

#Telegram Bot Configuration
telegram.bot-token=8613475410:AAHi_m8usDgiR5G0vnitAWmejXXZhkSPERw
telegram.chat-id=1786762813

#Bakong Configuration
bakong.api-url=https://api-bakong.nbc.gov.kh
bakong.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiMTRiNGQ0NjQxZGY4NGJjYiJ9LCJpYXQiOjE3NzcyMTc5MzEsImV4cCI6MTc4NDk5MzkzMX0.JiO16nbjy8d94B0kK5aKpdCfGvvrMVKKqPBTXLoHWJE

#Bakong Merchant Information
bakong.account-id=lean_kimlay@bkrt
bakong.merchant-id=lean_kimlay@bkrt
bakong.merchant-name=KIMLAY LEAN
bakong.merchant-city=PHNOM_PENH
bakong.acquiring-bank=BAKONG